from .common import SDCommonPage
from .config import ConfigPage
from .img2img import Img2ImgPage
from .inpaint import InpaintPage
from .preview import PreviewPage
from .txt2img import Txt2ImgPage
from .img_combined import CombinedPage
from .upscale import UpscalePage
from .controlnet import ControlNetPage
from .workflow import WorkflowPage